### ISSUE TITLE
Can't run on OpenSuse

### ISSUE THREAD

**Issue by ilovefreesw** [chartbrew/chartbrew#101]
I followed the installation using `npx` method. I am using OpenSuse Tumbleweed.

The first thing is that if we choose PostgreSQL as the database, then it should use 5432 as default port. Right now it uses 3306 which is default for MySQL.

![image](https://user-images.githubusercontent.com/77317006/135969502-214f5509-62e4-4b99-8c5d-937e0f0f024d.png)

The installation is successful, but can't run the app. There are errors on both; running the client as well the server.

Client error: `npm run start`

![image](https://user-images.githubusercontent.com/77317006/135969644-58a37559-64b0-4317-b94d-3b0788c14a3d.png)

Server error: `npm run start-dev`

![image](https://user-images.githubusercontent.com/77317006/135969680-a2e3cf8c-2ddd-423e-b719-69c664e9ed96.png)

**Comment by razvanilin** [comment]
hey @ilovefreesw thanks for pointing this out. Running with Postgres is still a new addition to the project and this installation step went under the radar. I'll create an issue and get on with fixing it as soon as I can

**Comment by razvanilin** [comment]
Also, for the error when running the server app, try running it like this instead: `npx nodemon index`

**Comment by ilovefreesw** [comment]
I think it is still failing.

![image](https://user-images.githubusercontent.com/77317006/135996634-d6ab4b84-8ab0-47f4-8feb-d07b7651e58c.png)

![image](https://user-images.githubusercontent.com/77317006/135996684-b3d0b5c2-84e1-475b-96d4-9690dfafec6e.png)

**Comment by razvanilin** [comment]
hmm, seems the installation didn't go as expected. Can you try to run `npm run setup` at the root of the project? That should install all the dependencies. Can you also let me know what OS and Node version are you using?

**Comment by ilovefreesw** [comment]
I am using OpenSuse Tumbleweed. Node: `16.6.2` and NPM: `7.24.2`

I am thinking of trying the Docker image now.

**Comment by ilovefreesw** [comment]
It looks like Docker image is also not supported. I think it is overall problem with the openSUSE. I think Docs should mention which Linux it works with.

![image](https://user-images.githubusercontent.com/77317006/136000505-b67544b3-aaa5-458f-847c-d05507ad4e76.png)

**Comment by razvanilin** [comment]
Thanks for trying that out! You're absolutely right about the docs. I'll look into it as soon as I can

**Comment by razvanilin** [comment]
@ilovefreesw forgot to keep this issue in the loop. There are two docker images now

* `razvanilin/chartbrew:latest` for `amd64` architecture - so this should work on your distro
* `razvanilin/chartbrew:latest-arm64` for `arm64` architecture - compatible with the M1 chips

The docs have been updated with instructions for each architecture: https://docs.chartbrew.com/deployment/#run-the-application-with-docker
