### ISSUE TITLE
Outdated docker images on Docker Hub

### ISSUE THREAD

**Issue by urlyb** [chartbrew/chartbrew#103]
The image for linux/amd64 was not updated for a year it seems. Based on the docker installation instructions, 1.0.0-beta.11 version of the Chartbrew gets installed.

https://hub.docker.com/r/razvanilin/chartbrew/tags

**Comment by razvanilin** [comment]
That's a good shout! I changed my main machine and I lost track of the different archs for the image. I'll check the environment on my old machine to see if I can get the image updated.

**Comment by razvanilin** [comment]
@urlyb I just update the docker images and they both run the latest version. The `latest` tag now has the amd64 arch and the `latest-arm64` has the arm64 arch.

The documentation has been updated to reflect this as well: https://docs.chartbrew.com/deployment/#run-the-application-with-docker

Thanks again for pointing this out!
