### ISSUE TITLE
Export to Excel doesn't work for data in Table View

### ISSUE THREAD

**Issue by urlyb** [chartbrew/chartbrew#104]
Version: 1.17.0 (docker linux/amd64)
Nothing happens if "Export to Excel" option is clicked from the Table View menu on the dashboard. It does work with the regular charts.

**Comment by razvanilin** [comment]
Hey @urlyb Apologies for the delay in getting back to you!

Could you inspect the Network tab in your browser's DevTools and let me know if there is an error message associated with the export request?

Also, if you can inspect the server logs inside the docker image to see if there are any errors there

**Comment by urlyb** [comment]
Hi @razvanilin. No problem about the delay. Great project btw.

You're right, I get HTTP 400 response from the server and this error description in the response:
**Response:** 
{"message":"field.replaceAll is not a function","error":"TypeError: field.replaceAll is not a function"}

**Request:** 
{"chartIds":[6],"filters":[{"id":"54a79281-0f93-46be-9ea3-29b7cfbb042d","field":"root[].ZACETEK_OBRAVNAVE","operator":"greaterOrEqual","value":"2021-10-01T00:00:00+02:00","projectId":"1","saved":false},{"id":"3f402676-07fc-4ba6-9373-03ea9783a929","field":"root[].ZACETEK_OBRAVNAVE","operator":"lessThan","value":"2021-11-01T00:00:00+01:00","projectId":"1","saved":false}]}

Docker logs command shows no errors.

**Comment by razvanilin** [comment]
This is very helpful, thanks! I'll look into it and fix it asap

**Comment by razvanilin** [comment]
@urlyb one more question:

For the table you want to export, did you exclude any fields? (like in the screenshot below)
If yes, can you let me know what the field is called? If that's sensitive info, feel free to also email it to me at raz(at)chartbrew(dot)com

![CleanShot 2021-11-16 at 10 38 14@2x](https://user-images.githubusercontent.com/5342321/141951356-392d562a-9e93-44ed-b73c-30704bfe3854.jpg)

**Comment by urlyb** [comment]
Yes, one field called "LETO" is excluded.

**Comment by razvanilin** [comment]
Awesome! and if you include the field, does the table export correctly? I think it may have to do something with the formatting of the excluded field, so need to be 100% sure that's where it fails.

**Comment by urlyb** [comment]
You're right, it does work with this field included.

**Comment by razvanilin** [comment]
I couldn't replicate the issue on my end, but I added type checks to make sure that the function doesn't fail anymore. I will let you know once I get home and push the fix to the Docker hub.

**Comment by urlyb** [comment]
Great! Thanks. If it helps - the values for this field are nothing special - just years:
![image](https://user-images.githubusercontent.com/43437803/141957563-61240c09-725e-4095-90c2-d61b53aaabb2.png)

**Comment by razvanilin** [comment]
I just pushed the fix to the `latest` tag. Feel free to update your image and let me know if the issue is fixed

**Comment by urlyb** [comment]
Works like a charm! This issue can be closed. Thanks.
