### ISSUE TITLE
Cannot upload custom logo since version 1.22

### ISSUE THREAD

**Issue by DrZoidberg09** [chartbrew/chartbrew#116]
I freshly updated to version 1.22 first with my own docker image, just now with yours. Now I cannot upload my own dashboard logo as it will spit out a internal server error. 

Before with version 1.21 everything was perfectly fine.

**Comment by razvanilin** [comment]
Hey @DrZoidberg09 thanks for reporting this. I was able to replicate the issue just now and will work on a fix

**Comment by razvanilin** [comment]
Hey @DrZoidberg09 the issue with the upload has been fixed in the latest release https://github.com/chartbrew/chartbrew/releases/tag/v1.22.1 

The error was triggered by a dependency update in 1.22.0
