### ISSUE TITLE
Chartbrew behind OAuth2

### ISSUE THREAD

**Issue by DrZoidberg09** [chartbrew/chartbrew#118]
Hi there,

I would like to access the dashboards from Nextcloud as external site but dont have them freely accessed from the web.

The idea was to use OAuth2 to proxy everything behind /b/ (where the dasboards are located).

However, if I want to acces the dashboard a white screen appears. Looking into the details shows three 400 bad request errors towards the api of chartbrew. Most notably, it tries to access {API URL}/team/oauth2. Then chartbrew answers that oauth2 team was not found for the sql request.

Any idea how to work with OAuth2 here?

Thanks a alot!

**Comment by razvanilin** [comment]
Hey,

Not really sure how your setup works exactly as I never used Nextcloud or attempted to proxy URLs like that.

Judging from the API call returning the `400`, your front-end address might be changed in a way that Chartbrew is not designed to work with. Chartbrew calls sometimes use the URL to get information (such as the team ID). Does your URL path in the frontend contain `/oauth2` by any chance?

**Comment by razvanilin** [comment]
Not sure this is application-related. I believe you will have to configure your web server to deal with the URL forwarding. I haven't done anything like this before so I will need to do some reading when I get some free time

**Comment by DrZoidberg09** [comment]
That would be nice. But this is surely not the number one priority. However, oauth2 compatibility would be nice. Maybe something for a long-term roadmap.

**Comment by theaccordance** [comment]
@razvanilin IF you were to consider federating authentication for your app, I would suggest OpenIDConnect as the protocol you implement.  

Why OpenIDConnect?  
* It's the successor to both OAuth (B2C federation) and SAML (B2B federation)
* It's still early in terms of adoption, but as an Okta customer (both work and my personal sandbox), I can configure integrations using the protocol.  Pretty sure other major vendors also support it at this point.  
* I'm not a B2C SSO expert (I am a B2B one though!) but I _think_ OpenIDConnect is backwards compatible with Oauth 2.0 providers.
