### ISSUE TITLE
Table chart can not show data set

### ISSUE THREAD

**Issue by gokcenveysel** [chartbrew/chartbrew#119]
Hi @razvanilin ,

I hope everything is fine!

I am using your **1.21.1** version of chartbrew to create some dashboards. 
But sometimes when I want to create a table chart, unfortunately, the table chart can not show the dataset on the table.

![Uploading Screen Shot 2022-06-29 at 10.29.09.png…]()

As you see the data set is ready and the query is working well on output but the table chart can not use this.

Do you have any idea why is working like this?

**Comment by razvanilin** [comment]
Hey @gokcenveysel!

Can you try to re-upload the screenshot? For some reason, I can't see it on my end.

One thing I will check first if the tables are not displaying properly, is to make sure you select the right **collection** field from the dataset settings. See the screenshot below:

![CleanShot 2022-06-29 at 09 39 43@2x](https://user-images.githubusercontent.com/5342321/176368983-b347fc84-7cfd-4b98-80b8-272fe387b004.jpg)

**Comment by gokcenveysel** [comment]
Hi @razvanilin ,

Thanks for quick response.

Of course, I upload the screenshot again.

<img width="1509" alt="Screen Shot 2022-06-29 at 12 34 25" src="https://user-images.githubusercontent.com/11418591/176391618-ce4106da-3c6f-4cd3-801b-a833d3d9a78c.png">

**Comment by razvanilin** [comment]
Can you try to uncheck the **Use cache** checkbox next to the "Re-process data" button, then press the button and see if it works? I believe the data that is cached has the format that's used for Axis Charts and it needs to be updated for a table view.

Let me know if that works

**Comment by gokcenveysel** [comment]
Unfortunately, it does not working.

<img width="1484" alt="Screen Shot 2022-06-29 at 12 42 15" src="https://user-images.githubusercontent.com/11418591/176392960-774a851e-6818-4fe1-97a2-ab1f98ee65eb.png">

**Comment by gokcenveysel** [comment]
Yes, the query of the collection is working and I see the results.

<img width="1681" alt="Screen Shot 2022-06-29 at 12 45 42" src="https://user-images.githubusercontent.com/11418591/176393814-5d341597-f7bb-4934-968b-c5c38911f75c.png">

**Comment by razvanilin** [comment]
Can you try to switch to a Line or Bar chart, click on "re-process data" and then send me a screenshot? I want to see if I can spot any error in the UI

**Comment by gokcenveysel** [comment]
Of course, when I change the charts its works but just the table chart not working

<img width="1521" alt="Screen Shot 2022-06-29 at 12 50 15" src="https://user-images.githubusercontent.com/11418591/176394739-55ef9f52-a799-43df-9320-bff01e300c95.png">

**Comment by razvanilin** [comment]
Can you click on those requests and see if you get any error messages in the "Preview" tab?

**Comment by gokcenveysel** [comment]
It gave the same preview as below.

<img width="959" alt="Screen Shot 2022-06-29 at 13 48 18" src="https://user-images.githubusercontent.com/11418591/176407076-5df5831f-37ed-4580-b2be-3579e65cbdde.png">

**Comment by gokcenveysel** [comment]
Hey @razvanilin ,

I take a look for change encoding to utf8mb4 but I think, in MongoDB UTF-8 is the default encoding charset. And in MongoDB UTF-8 is the same as MySQL utf8mb4.

As you can see in this link: https://stackoverflow.com/questions/26167421/is-it-possible-to-store-utf8-mb4-in-mongodb

Is there any other solution?

By the way, I am using Mongo Compass for visualize data

**Comment by gokcenveysel** [comment]
Oh, I understood what you mean now. Actually, I am using PostgreSQL not MySQL. And I will check the PostgreSQL using for Chartbrew. May I change all of the charsets of the table? Or just a specific table will enough for it?

**Comment by razvanilin** [comment]
I'm a Postgres noob and I don't know for sure how to do it. I google something and found this article which seems to be the way forward https://tutorials.technology/tutorials/How-to-change-postgresql-database-encoding-to-UTF8-from-SQL_ASCII.html

Not sure if it's possible to do it just for a table

**Comment by razvanilin** [comment]
Hey @gokcenveysel I think I fixed the issue with the table view with the latest changes on the `master` branch. I managed to replicate the issue when the table has some empty values at the start of the dataset. The code now checks for these to make sure it doesn't stop the table from being properly generated.

If you can pull the changes from `master`, feel free to give it a try and let me know if it fixes the issue for you.

**Comment by razvanilin** [comment]
closing this, but feel free to re-open if the issue persists
