### ISSUE TITLE
menu Content is not fully visible 

### ISSUE THREAD

**Issue by scottdevopsgithub** [chartbrew/chartbrew#120]
Just got everything running locally on a Windows 10 machine. Was trying out the Chartbrew application and noticed this potential issue. It will be easiest if you just look at the screenshot to see what I noticed.

![error-content not showing](https://user-images.githubusercontent.com/96550228/177045550-d7feb322-4564-44e9-b0f3-9f779211fbff.png)

**Comment by razvanilin** [comment]
Hey @scottdevopsgithub thanks for reporting this!

I just looked into it and traced the issue to a dependency that I updated in the last release. This is fixed now as of [12e1348](https://github.com/chartbrew/chartbrew/commit/12e13484eadd1d8b8d649ccdb9f5db3f83cdf91b)

**Comment by scottdevopsgithub** [comment]
awesome, thanks for fixing so quickly!
