### ISSUE TITLE
Windows Dev - deploy to vercel and netlify not working

### ISSUE THREAD

**Issue by scottdevopsgithub** [chartbrew/chartbrew#121]
I will put 3 screenshots in here in relation to a deployment issue (about a file-loader?). I have not encountered this type of problem before. The /client side of the locally running (self-hosted) chartbrew app is not compiling apparently. But I did get the /server side of the code to be deployed and running on heroku (and the /server side of the code is also running locally on my Dev Pc). And also the mysql database is up and running on heroku too. So it is just the /client side code that is giving the problem I encountered, because everything else seems to be running fine.

So I have the chartbrew up and running locally on a Windows 10 Dev PC. To save a little time, I just pointed my local running version of chartbrew, at a mysql database running on heroku.  I used the .env variables on my local machine to point at the heroku instance for the database. 

However, when I have tried to deploy (my copy) of chart brew (the client side of course) to netlify and vercel, I get the same type of error message you see in the screenshots from both of those cloud providers. 

I have been doing research on it, but so far do not know how to fix it. Thought I would mention it, in case someone else might have this issue or maybe already has.  I will keep looking into it, to see if I cant get this client side code to be running on vercel and/or netlify.

![error-deploy-on-netlify](https://user-images.githubusercontent.com/96550228/177062221-e72e2b64-9d2a-4fd4-9f60-974450168a22.png)

![error-2-deploy-on-netlify](https://user-images.githubusercontent.com/96550228/177062231-fd73afd1-dd78-4193-a13b-9fe943dffffa.png)

![error-3-deploy-on-netlify](https://user-images.githubusercontent.com/96550228/177062234-49780016-a886-480b-b18b-de10183b66b2.png)

**Comment by razvanilin** [comment]
Thanks for reporting! I will give it a try as soon as possible and see if this is related to another dependency

**Comment by razvanilin** [comment]
Can you pull the latest changes from `master` and then try to re-deploy again? The issue should be fixed now

**Comment by scottdevopsgithub** [comment]
I will give it a try. At the moment, I am using just a copy of the code I downloaded as a zip file and self-hosted it that way.  In the meantime, I will take a look at what changes you committed. If its simple enough, I can just apply the same changes to my offline copy of the code. And see what happens.

**Comment by scottdevopsgithub** [comment]
OK, YaY that appears to have fixed it! After pulling down latest code, updating my env file as needed, and then I deployed it (from my repo) to vercel....I was able to login on the Chratbrew login page on my vercel account/app. 

So the fact that my login page on vercel let me login, proves that my self-hosted chartbrew backend on heroku is up and running fine. Thanks for your help!!

**Comment by razvanilin** [comment]
Glad to hear it's working! I'll close this issue for now 👍
