### ISSUE TITLE
Exporting to pdf ?

### ISSUE THREAD

**Issue by scottdevopsgithub** [chartbrew/chartbrew#123]
I saw this pdf export option mentioned on the website. I checked/searched the chartbrew repo, and also the docs, and didnt really see too much about it. I know you can do a print preview, and choose a PDF export that way.  But I was thinking there would be an option on a popup menu that says "Export to PDF'. 

![image](https://user-images.githubusercontent.com/96550228/177586054-664ad258-c011-4ff2-b599-648f6c3deb06.png)

**Comment by razvanilin** [comment]
Currently, it's only possible to export to PDF through the PDF viewer in each project. Can you let me know how you would expect this to work? This way I can get some new ideas about the usage as I'm not using the PDF export myself

**Comment by scottdevopsgithub** [comment]
I mainly was just wondering, if there was supposed to an option to export to pdf, based on that screenshot. And if I just was missing it somehow.  I thought the option to export to pdf would just show up in the same menu where you see the export to excel option.
