### ISSUE TITLE
Click on Chartbrew 1.22.1 - get a 404

### ISSUE THREAD

**Issue by scottdevopsgithub** [chartbrew/chartbrew#125]
When in the Chartbrew dashboard, I clicked on the link that shows the version of Chartbrew (1.22.1) and it gave a 404 not found.

![image](https://user-images.githubusercontent.com/96550228/178110765-102ca5eb-a200-42bd-be19-0b71d76fad85.png)

**Comment by razvanilin** [comment]
Thanks for reporting! This happens because there is no "v" before the version number. It's a weird behavior when building the front-end with a different version of NodeJS.  I think I'll just need to check if the V is there and add it if it's not (in the UI)
