### ISSUE TITLE
No hover effect on button

### ISSUE THREAD

**Issue by ayush-wd** [chartbrew/chartbrew#132]
![image](https://user-images.githubusercontent.com/83002299/184295572-3b381e35-22e9-43ab-acd1-33489317aa9a.png)

The button mentioned in the screenshot above does not change its gradient when the cursor hovers over it unlike all other buttons with the same background.

I can solve this issue.

**Comment by razvanilin** [comment]
Hey @ayush-wd appreciate your help with this, but chartbrew's landing page is not part of this open-source repository. The code is closed source and only the Chartbrew team can access it.
