### ISSUE TITLE
CB_DB_PORT not documented correctly in Docker instructions

### ISSUE THREAD

**Issue by matthewdenison** [chartbrew/chartbrew#146]
Hi, I was trying to connect to a MySQL server using the Chartbrew Docker image. My first-time experience was really smooth except for one minor issue. In the documentation located at https://docs.chartbrew.com/deployment/#run-the-application-with-docker it says you can append the port number to the host address but that doesn't work. After looking at https://github.com/chartbrew/chartbrew/blob/master/.env-template I noticed the CB_DB_PORT that I could set instead. After using that I stopped getting DNS errors and was able to connect. It would be helpful to update the documentation for other newcomers like myself.

**Comment by razvanilin** [comment]
Thanks for spotting this, will fix soon 👌
