### ISSUE TITLE
default user for the first login - signup error

### ISSUE THREAD

**Issue by lidernetworktecnologia** [chartbrew/chartbrew#148]
![chartbrew fw](https://user-images.githubusercontent.com/84813748/207345834-78f213c6-3938-4ffb-bff5-10bd44146b6c.png)
Hello mentors,
After first installing chartbrew using the docker command docker run -p 4019:4019 -p 4018:4018 -e CB_SECRET=secret -e CB_API_HOST=0.0.0.0 -e CB_API_PORT=4019 -e CB_DB_HOST=192.168.88.201 -e CB_DB_PORT =6603 -e CB_DB_NAME=chartbrew -e CB_DB_USERNAME=root -e CB_DB_PASSWORD=pass -e REACT_APP_CLIENT_HOST=http://localhost:4018 -e REACT_APP_API_HOST=http://localhost:4019 razvanilin/chartbrew

I can't perform the first access - signup, I go to the page to create a new user and the message appears: Failed to fetch, accessing the database I can see the tables that were created which means that access to the database is functional . Which default user for the first login?

**Comment by razvanilin** [comment]
Hi @lidernetworktecnologia can you check the logs inside the docker container to see what you are getting over there?

One things I would also check is if the application can reach your database host from the container. If the database cannot be reached, you should be able to see some errors in the logs.

If using the cli tool you can see the logs like this:

```
docker logs <your_container_name>
```

**Comment by ntmxglrtayl03** [comment]
So did I,I set the ipv4 at startup , But it's still requesting localhost
```yml
docker run -d -p 4019:4019 -p 4018:4018 \
  -e CB_SECRET=enter_a_secure_string \
  -e CB_API_HOST=0.0.0.0 \
  -e CB_API_PORT=4019 \
  -e CB_DB_HOST=mysqlip\
  -e CB_DB_PORT=3306 \
  -e CB_DB_NAME=chartbrew \
  -e CB_DB_USERNAME=root \
  -e CB_DB_PASSWORD=password \
  -e REACT_APP_CLIENT_HOST=http://ipv4:4018 \
  -e REACT_APP_API_HOST=http://ipv4:4019 \
  razvanilin/chartbrew
```
![image](https://user-images.githubusercontent.com/114506067/211202790-61673cba-1322-4402-8229-f13c32fa4100.png)
![image](https://user-images.githubusercontent.com/114506067/211202648-3c8f1dd3-61eb-48ce-897e-b970aba13abb.png)

**Comment by karlis-ozo** [comment]
This is related to the fact that you currently hace to rebuild the static content if you don't use localhost or decide to change any of the 2 URLs or ports

https://github.com/chartbrew/chartbrew/issues/139#issuecomment-1267932621

**Comment by ntmxglrtayl03** [comment]
I think this is a misleading document，It tells me to rebuild when I need to use a new environmental，I think it should be described as, "When you need to make environment variables valid."
![image](https://user-images.githubusercontent.com/114506067/211229192-01ba9a8b-3792-4f4f-8709-09c0445cd4ce.png)

**Comment by razvanilin** [comment]
Hey @ntmxglrtayl03 the documentation says that if you change the environment variables after the first run, you will need to rebuild the UI. This is mandatory so the UI doesn't get rebuilt when pulling a new version of the image because this causes the application to hang, causing downtime while building.

I'll give an example of when the UI needs to be rebuilt:

1. Pull & Run the image for the first time with the first set of variables
2. Decide to change `REACT_APP_API_HOST` to another value and run `docker run <new_vars>` again
3. The client app still uses the old version of `REACT_APP_API_HOST` and the UI needs to be rebuilt
4. 👇
```
# replace 'your_container_name' with the name of your docker container where Chartbrew is running

docker exec -it -w /code/client your_container_name npm run build
```

Let me know if this still happens even after rebuilding the UI

**Comment by gentitope** [comment]
@razvanilin i setup this image in kubernetes and also rebuild with `npm run build` because im using my endpoint url for REACT_APP_CLIENT_HOST and REACT_APP_API_HOST. 
I am still getting `Failed to fetch` error.

Find `npm run build` error below:

```
root@chartbrew-8cb6778bf-hwvjb:/code/client# npm run build

> client@2.3.0 build /code/client
> npm run setup && cross-env REACT_APP_VERSION=$npm_package_version node scripts/build.js


> client@2.3.0 setup /code/client
> echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true

cp: overwrite 'src/config/settings.js'? Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@2.3.0 build: `npm run setup && cross-env REACT_APP_VERSION=$npm_package_version node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@2.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-11T11_50_51_277Z-debug.log
```

**Comment by razvanilin** [comment]
Hey @gentitope I'm not familiar with kubernetes. Are you using the docker image to set it up over there?

**Comment by gentitope** [comment]
Hello @razvanilin yes..i setup it using the docker image. Thanks

**Comment by gentitope** [comment]
Hello @razvanilin i was able to run `npm run build` successfully when i increase k8s POD memory to `4G`. Everything working as expected. Thanks

**Comment by benngagne** [comment]
I was having the same issue trying to run the docker container on a seperate machine. By rebuilding the UI it fixed the fetch error issue I was having and started sending the API requests to the correct address. Now I am getting an Invalid Token error when trying to signup or login. Any thoughts?

**Comment by karlitos-ozo** [comment]
check the Console and Network tabs in developer console. you will probably see some errors there.
also make sure you use the latest docker image. It rebuilds on every start so if it doesn't work right from start, just check the docker logs, if it is still rebuilding

**Comment by gentitope** [comment]
@benngagne if you change `REACT_APP_CLIENT_HOST` and `REACT_APP_API_HOST ` to something else than `localhost` then try this docker image `gentitope/chartbrew:1.1` and make sure you have enough memory for your container.

**Comment by razvanilin** [comment]
Closing this for now as it seems to be solved by the automatic rebuilds in the current docker image 👍

**Comment by mz0in** [comment]
Hi , I am facing the same problem using the new docker image using the provided docker run command without changing the local host settings , any advice ?

**Comment by karlis-ozo** [comment]
here you go, a working example. things such as ${CB_SECRET} are environment variables as we use GitHub secrets.
Well I actually haven't tested with he latest version. 
https://github.com/Freelancers-Union/FUBot/blob/master/chartbrew-compose.yml

The docker version currently works in a way that in beginning it will server assuming API lives at localhost(relative to browser). But the client is rebuilt as well when the container starts so it may take some time for the site to start working.
check out your container logs for more info
here are my  logs:
![image](https://user-images.githubusercontent.com/52657221/224046366-cd2862cf-7a44-4a61-8fdc-e62b9e3bac39.png)

And after some while this shoes up in the logs. after this it works as it should.
![image](https://user-images.githubusercontent.com/52657221/224046684-6c5068d3-30ec-448b-8b07-ef5e885b8d67.png)

**Comment by razvanilin** [comment]
Just made a note to update the compose file to use it properly with the env variables. Thanks for sharing your example @karlis-ozo 🙏

**Comment by c-nv-s** [comment]
> here you go, a working example. things such as ${CB_SECRET} are environment variables as we use GitHub secrets. Well I actually haven't tested with he latest version. https://github.com/Freelancers-Union/FUBot/blob/master/chartbrew-compose.yml
> 
> The docker version currently works in a way that in beginning it will server assuming API lives at localhost(relative to browser). But the client is rebuilt as well when the container starts so it may take some time for the site to start working. check out your container logs for more info here are my logs: ![image](https://user-images.githubusercontent.com/52657221/224046366-cd2862cf-7a44-4a61-8fdc-e62b9e3bac39.png)
> 
> And after some while this shoes up in the logs. after this it works as it should. ![image](https://user-images.githubusercontent.com/52657221/224046684-6c5068d3-30ec-448b-8b07-ef5e885b8d67.png)

thanks, you may have saved the situation for them... I'll maybe retry on the weekend

**Comment by bytepure** [comment]
```
docker run  \
  ... \
  -e VITE_APP_CLIENT_HOST=http://localhost:4018 \
  -e VITE_APP_CLIENT_PORT=4018 \
  -e VITE_APP_API_HOST=http://localhost:4019 \
  --name chartbrew_server \
  razvanilin/chartbrew
```

change your ip, example
```
  -e VITE_APP_CLIENT_HOST=http://192.168.100.101:4018 \
  -e VITE_APP_CLIENT_PORT=4018 \
  -e VITE_APP_API_HOST=http://192.168.100.101:4019 \
```
