### ISSUE TITLE
Feature Suggestion: run inside Jupyter with S3 parquet support?

### ISSUE THREAD

**Issue by ilyanoskov** [chartbrew/chartbrew#164]
A lot of the analytical work is tightly coupled with Jupyter notebooks / DataFrames / files on S3. I have recently discovered https://github.com/Kanaries/pygwalker and thought that is one of the best implementations for embeddable analytics apps. 

Do you think it would be possible to do something similar with chartbrew?

**Comment by razvanilin** [comment]
Hey @ilyanoskov, thanks for dropping by. I'm not that familiar with the technologies, but will take a look and update here later 👍
