### ISSUE TITLE
[documentation] Is there a visual to explain the tech architecture ?

### ISSUE THREAD

**Issue by stillhope** [chartbrew/chartbrew#169]
I am trying to understand the technical architecture of chatbrew as a non-dev.  Is there a visual anywhere?

UI layer (dashboard of graph and table widgets) (? any map widgets)
Translation layer ?? is there one. 
Connector layer (api connectors, db connectors etc..)
Data layer (individual data-sets, joined data-sets, db etc..) -- self-hosted, cloud, proprietary or open-source

Are all the business rules stored within the dashboard element design?

**Comment by razvanilin** [comment]
Hey @stillhope there's no detailed explanation of the architecture because it will be a nightmare to maintain from our side. Not sure why this information is necessary, seems awfully specific. Can you let me know what's the use case you need this for?

* You can find all the integrations available for Chartbrew here: https://chartbrew.com/product/integrations
* Documentation site: https://docs.chartbrew.com
* The platform can be self-hosted for free or trialed for free without self-hosting

**Comment by stillhope** [comment]
Specific ?  Actually the opposite for me. I am trying to get the big picture, the how it works from a user perspective. Maybe as your dev your thinking detail architecture. I am not.  I thought this style of question would be welcome in open source apps and a no-brainer. 

Esp important when an SME uses a tool that will likely become critical to their business operations.

**Comment by razvanilin** [comment]
Is there an example from another open-source platform like Chartbrew that you can share? That will give me a better idea of what you're looking for.

**Comment by stillhope** [comment]
Oh I do not know as have not searched.  At the moment in our group most are using Tableau and struggling to some level or another.  But the graphical elements are great. Being the most app savvy in group, they asked me to take a peek at this option. I am an application person but from way back pre-internet boom...  so perhaps my question is out-of-date.

**Comment by stillhope** [comment]
In the apps I reviewed today, one had such a similar visual. They call their visual 'Below is a representation of the logical architecture.' as the app relates to security.  The visual I am after is of the application model as it relates to presentation layer (dashboard) for decision making
https://getsentinel.io/security-model

**Comment by razvanilin** [comment]
Thanks for the link, that helps. I will see if I can spare some time in the coming days to look over this. In the meantime, I think using the app for a bit should clarify most of the questions
