### ISSUE TITLE
Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by Nadir-info2016** [chartbrew/chartbrew#170]
![image](https://user-images.githubusercontent.com/93675935/231599125-94b6d399-b9c4-4139-b603-61008c728f7b.png)
![image](https://user-images.githubusercontent.com/93675935/231599207-0ea59b2f-faba-4aa0-8a16-53e5279688cc.png)

I use docker-compose installation. I tried different variants of npm as well. For designing, I use a template with instructions and apache2.4. I can't understand the reason, please help!

**Comment by razvanilin** [comment]
Hey @Nadir-info2016 

That looks like the client application cannot reach the backend app of Chartbrew. The first place I'd look at are the env variables, especially the ones starting with `REACT_`

For example your `REACT_APP_API_HOST` variable should contain a host that you can access through your browser. So if you cannot reach the API host from your browser, you'll need to change that variable to an address that works (domain, IP, etc).

Also, check this helpful comment with an example of docker-compose: https://github.com/chartbrew/chartbrew/issues/148#issuecomment-1462109085

Let me know how it goes :)

**Comment by mapdeep** [comment]
I am experiencing the same issue. Is there any workaround for this?

**Comment by razvanilin** [comment]
Hey @mapdeep I think the your API host `REACT_APP_API_HOST` variable is pointing towards your client application rather than API.

Can you also check the `Preview` tab in the devtools to see if the response is the actual user details?
