### ISSUE TITLE
Unable to signup after deploying on render

### ISSUE THREAD

**Issue by ajmeraaxesh** [chartbrew/chartbrew#172]
Hi I followed your tutorial over here for deploying to render :

https://chartbrew.com/blog/how-to-deploy-chartbrew-on-render/?ref=chartbrew-blog

However when trying to signup. I am facing issues. I am not seeing any error or anything I have followed all the steps suggested in the link above.

Frontend url
https://chartbrew-frontend-9hym.onrender.com

**Comment by razvanilin** [comment]
Hey @ajmeraaxesh I just gave a try and try to find the issue on your site. The error appears after a while, which most likely means that your backend service might not be able to connect to the database properly.

You can get more details into what's happening if you go to the chartbrew `Web Service` application in your render dashboard, then click on `Logs` to inspect what's going on. Can you let me know if you see any errors there?
