### ISSUE TITLE
ADD 404 Page

### ISSUE THREAD

**Issue by azizlimonu** [chartbrew/chartbrew#179]
I have observed that there is no 404 page, whenever we search for an unknown route in the url its just look like this
![chatbew](https://github.com/chartbrew/chartbrew/assets/106480374/670d6841-845c-43d4-8767-2c35d0c2f8d2)

can i contribute on this feature? thanks

**Comment by razvanilin** [comment]
Hey @azizlimonu thanks for letting us know!

I appreciate the interest, but the chartbrew.com website is not part of this repository. It's also not open source and cannot accept external contributions for now.
