### ISSUE TITLE
× NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by kuiniela** [chartbrew/chartbrew#180]
**First I created the database chartbrew
It reminds me:**
unknown column sort...
SELECT `Chart`.`id`, `Chart`.`project_id`, `Chart`.`name`, `Chart`.`lastAutoUpdate`, `Chart`.`autoUpdate`, `Chart`.`chartData`, `Datasets`.`id` AS `Datasets.id`, `Datasets`.`chart_id` AS `Datasets.chart_id`, `Datasets`.`connection_id` AS `Datasets.connection_id`, `Datasets`.`query` AS `Datasets.query`, `Datasets`.`xAxis` AS `Datasets.xAxis`, `Datasets`.`xAxisOperation` AS `Datasets.xAxisOperation`, `Datasets`.`yAxis` AS `Datasets.yAxis`, `Datasets`.`yAxisOperation` AS `Datasets.yAxisOperation`, `Datasets`.`dateField` AS `Datasets.dateField`, `Datasets`.`datasetColor` AS `Datasets.datasetColor`, `Datasets`.`fillColor` AS `Datasets.fillColor`, `Datasets`.`fill` AS `Datasets.fill`, `Datasets`.`multiFill` AS `Datasets.multiFill`, `Datasets`.`dateFormat` AS `Datasets.dateFormat`, `Datasets`.`legend` AS `Datasets.legend`, `Datasets`.`pointRadius` AS `Datasets.pointRadius`, `Datasets`.`patterns` AS `Datasets.patterns`, `Datasets`.`conditions` AS `Datasets.conditions`, `Datasets`.`formula` AS `Datasets.formula`, `Datasets`.`fieldsSchema` AS `Datasets.fieldsSchema`, `Datasets`.`excludedFields` AS `Datasets.excludedFields`, `Datasets`.`groups` AS `Datasets.groups`, `Datasets`.`groupBy` AS `Datasets.groupBy`, `Datasets`.`sort` AS `Datasets.sort`, `Datasets`.`columnsOrder` AS `Datasets.columnsOrder`, `Datasets`.`averageByTotal` AS `Datasets.averageByTotal`, `Datasets`.`configuration` AS `Datasets.configuration`, `Datasets`.`joinSettings` AS `Datasets.joinSettings`, `Datasets`.`main_dr_id` AS `Datasets.main_dr_id`, `Datasets`.`order` AS `Datasets.order`, `Datasets`.`maxRecords` AS `Datasets.maxRecords`, `Datasets`.`createdAt` AS `Datasets.createdAt`, `Datasets`.`updatedAt` AS `Datasets.updatedAt` FROM `Chart` AS `Chart` LEFT OUTER JOIN `Dataset` AS `Datasets` ON `Chart`.`id` = `Datasets`.`chart_id` WHERE `Chart`.`autoUpdate` > 0;
**So I added them in turn sort，columnsOrder，averageByTotal，configuration，joinSettings，order，maxRecords**
**It reminds me that it is duplicated failed
omg,so I delete them in turn sort**
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
Running server on port 4019
Updated database schema to the latest version!
**But!!**
**### A problem is displayed after registration：**

removeChild
node_modules/react-dom/cjs/react-dom.development.js:10301
unmountHostComponents
node_modules/react-dom/cjs/react-dom.development.js:21296
commitDeletion
node_modules/react-dom/cjs/react-dom.development.js:21347
commitMutationEffects
node_modules/react-dom/cjs/react-dom.development.js:23407
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:4056
commitRootImpl
node_modules/react-dom/cjs/react-dom.development.js:23121
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js:11276
commitRoot
node_modules/react-dom/cjs/react-dom.development.js:22990
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:22329
(anonymous function)
node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js:11309
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:21893
dispatchAction
node_modules/react-dom/cjs/react-dom.development.js:16139
▲ 19 stack frames were expanded.
submitUser
src/containers/Signup.js:85
  82 |   return;
  83 | }
  84 | 
> 85 | setLoading(true);
     | ^  86 | if (params.has("inviteToken")) {
  87 |   _createInvitedUser({ name, email, password }, params.get("inviteToken"));
  88 | } else {
View compiled
onPress
node_modules/@nextui-org/react/esm/button/button.js:1
triggerPressEnd
src/usePress.ts:180
  177 | 
  178 | setPressed(false);
  179 | 
> 180 | if (onPress && wasPressed && !isDisabled) {
      | ^  181 |   onPress({
  182 |     type: 'press',
  183 |     pointerType,
View compiled
HTMLDocument.onPointerUp
src/usePress.ts:412
  409 | 
  410 | let onPointerUp = (e: PointerEvent) => {
  411 |   if (e.pointerId === state.activePointerId && state.isPressed && e.button === 0) {
> 412 |     if (isOverTarget(e, state.target)) {
      | ^  413 |       triggerPressEnd(createEvent(state.target, e), state.pointerType);
  414 |     } else if (state.isOverTarget) {
  415 |       triggerPressEnd(createEvent(state.target, e), state.pointerType, false);
View compiled

**Comment by razvanilin** [comment]
hey @kuiniela thanks for dropping by! Would you be able to:

1. Please format the errors with the `code` block in the Github text editor so I can see clearly your comments and the error messages.
2. Describe how you ran the project and how you got to these errors
3. Can you also let me know what operating system you're using and the Node version?
