### ISSUE TITLE
Error creating the first user in a docker compose setup

### ISSUE THREAD

**Issue by stevennt** [chartbrew/chartbrew#181]
I got this  error while pulling the source code, editing the .env and running the docker compose. 
- The UI comes up, but the docker compose terminal shows this error. 
- Signing up as the first user is not succeeding. The error is: Unexpected token '<', "<!doctype "... is not valid JSON

Anyone in the same situation? Thanks.

![image](https://github.com/chartbrew/chartbrew/assets/32351181/c8a20b80-f8cc-4dd7-a483-a75f74525b0e)

Docker logs showed: 

2023-07-05T02:17:41.020627Z 0 [Note] mysqld: ready for connections.
Version: '5.7.41'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2023-07-05T02:17:56.302968Z 4 [Note] Aborted connection 4 to db: 'chartbrew' user: 'admin' host: '172.25.0.3' (Got an error reading communication packets)
2023-07-05T02:17:56.302968Z 6 [Note] Aborted connection 6 to db: 'chartbrew' user: 'admin' host: '172.25.0.3' (Got an error reading communication packets)
2023-07-05T02:17:56.302973Z 3 [Note] Aborted connection 3 to db: 'chartbrew' user: 'admin' host: '172.25.0.3' (Got an error reading communication packets)
2023-07-05T02:17:56.303015Z 5 [Note] Aborted connection 5 to db: 'chartbrew' user: 'admin' host: '172.25.0.3' (Got an error reading communication packets)
2023-07-05T02:27:19.775476Z 0 [Note] Giving 0 client threads a chance to die gracefully
2023-07-05T02:27:19.775559Z 0 [Note] Shutting down slave threads
2023-07-05T02:27:19.775571Z 0 [Note] Forcefully disconnecting 0 remaining clients

chartbrew_1  | The UI is rebuilding. Please wait...
chartbrew_1  | 
chartbrew_1  | > client@2.6.2 build /code/client
chartbrew_1  | > npm run setup && cross-env REACT_APP_VERSION=$npm_package_version node scripts/build.js
chartbrew_1  | 
chartbrew_1  | 
chartbrew_1  | > client@2.6.2 setup /code/client
chartbrew_1  | > echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true
chartbrew_1  | 
db_1         | 2023-07-05T06:53:29.778114Z 0 [Note] Event Scheduler: Loaded 0 events
db_1         | 2023-07-05T06:53:29.778248Z 0 [Note] mysqld: ready for connections.
db_1         | Version: '5.7.41'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
chartbrew_1  | cp: overwrite 'src/config/settings.js'? Running server on port 4019
db_1         | 2023-07-05T06:53:31.407633Z 3 [Note] InnoDB: Stopping purge
db_1         | 2023-07-05T06:53:31.474617Z 3 [Note] InnoDB: Resuming purge
chartbrew_1  | Creating an optimized production build...
chartbrew_1  | Browserslist: caniuse-lite is outdated. Please run:
chartbrew_1  |   npx browserslist@latest --update-db
chartbrew_1  |   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
chartbrew_1  | Error while cleaning the chart caches. You might want to delete them manually
chartbrew_1  | (node:9) UnhandledPromiseRejectionWarning: Error
chartbrew_1  |     at Query.run (/code/server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
chartbrew_1  |     at /code/server/node_modules/sequelize/lib/sequelize.js:315:28
chartbrew_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
chartbrew_1  |     at async MySQLQueryInterface.select (/code/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
chartbrew_1  |     at async Function.findAll (/code/server/node_modules/sequelize/lib/model.js:1140:21)
chartbrew_1  | (Use `node --trace-warnings ...` to show where the warning was created)
chartbrew_1  | (node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
chartbrew_1  | (node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
chartbrew_1  | npx: installed 91 in 16.255s
chartbrew_1  |  INFO  Accepting connections at http://localhost:4018
chartbrew_1  | (node:9) UnhandledPromiseRejectionWarning: Error
chartbrew_1  |     at Query.run (/code/server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
chartbrew_1  |     at /code/server/node_modules/sequelize/lib/sequelize.js:315:28
chartbrew_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
chartbrew_1  |     at async MySQLQueryInterface.select (/code/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
chartbrew_1  |     at async Function.findAll (/code/server/node_modules/sequelize/lib/model.js:1140:21)
chartbrew_1  | (node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
chartbrew_1  | Updated database schema to the latest version!
chartbrew_1  | Compiled with warnings.

**Comment by razvanilin** [comment]
Hi there,
Are you using the browser on the same machine as the docker container?

**Comment by stevennt** [comment]
> Hi there, Are you using the browser on the same machine as the docker container?

Yes I run docker compose, and Chrome to access the UI: all on the same machine.

**Comment by stevennt** [comment]
Ok the following trick worked for me:
- In the docker-compose.yml file, add a network for the two containers to use
- In the .env file, make sure that CB_API_HOST=0.0.0.0 and NOT CB_API_HOST=localhost

This is applicable to the docker-compose setup.
If you like, I can submit a PR.
