### ISSUE TITLE
Installation/Setup fails when using custom database name

### ISSUE THREAD

**Issue by sun** [chartbrew/chartbrew#182]
Problem
* When not using the predefined database name `chartbrewdev` for the dev server, then `npm run start-dev` fails with many SQL errors.

Cause
* The database migrations are not executed on the database if its name is different from `chartbrewdev`.

Workaround
* Use the default database names as they are defined in the `.env` example/template file.

**Comment by razvanilin** [comment]
Hi there, can you please place the SQL errors here as well? That will help to see what's actually going on

**Comment by rdr6000** [comment]
Running for the first time with postgres in windows using git bash. The database is chartbrewdev:

Running server on port 4019
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Query.run (C:\*path*\chartbrew\server\node_modules\sequelize\lib\dialects\postgres\query.js:50:25)
    at C:\*path*\chartbrew\server\node_modules\sequelize\lib\sequelize.js:315:28
    at async PostgresQueryInterface.select (C:\*path*\chartbrew\server\node_modules\sequelize\lib\dialects\abstract\query-interface.js:407:12)
    at async Chart.findAll (C:\*path*\chartbrew\server\node_modules\sequelize\lib\model.js:1140:21) {
  name: 'SequelizeDatabaseError',
  parent: error: relation "Chart" does not exist
      at Parser.parseErrorMessage (C:\*path*\chartbrew\server\node_modules\pg-protocol\dist\parser.js:287:98)
      at Parser.handlePacket (C:\*path*\chartbrew\server\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (C:\*path*\chartbrew\server\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (C:\*path*\chartbrew\server\node_modules\pg-protocol\dist\index.js:11:42)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 106,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '1359',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1381',
    routine: 'parserOpenTable',
    sql: 'SELECT "Chart"."id", "Chart"."project_id", "Chart"."name", "Chart"."lastAutoUpdate", "Chart"."autoUpdate", "Chart"."chartData", "ChartDatasetConfigs"."id" AS "ChartDatasetConfigs.id", "ChartDatasetConfigs"."chart_id" AS "ChartDatasetConfigs.chart_id", "ChartDatasetConfigs"."dataset_id" AS "ChartDatasetConfigs.dataset_id", "ChartDatasetConfigs"."formula" AS "ChartDatasetConfigs.formula", "ChartDatasetConfigs"."datasetColor" AS "ChartDatasetConfigs.datasetColor", "ChartDatasetConfigs"."fillColor" AS "ChartDatasetConfigs.fillColor", "ChartDatasetConfigs"."fill" AS "ChartDatasetConfigs.fill", "ChartDatasetConfigs"."multiFill" AS "ChartDatasetConfigs.multiFill", "ChartDatasetConfigs"."legend" AS "ChartDatasetConfigs.legend", "ChartDatasetConfigs"."pointRadius" AS "ChartDatasetConfigs.pointRadius", "ChartDatasetConfigs"."excludedFields" AS "ChartDatasetConfigs.excludedFields", "ChartDatasetConfigs"."sort" AS "ChartDatasetConfigs.sort", "ChartDatasetConfigs"."columnsOrder" AS "ChartDatasetConfigs.columnsOrder", "ChartDatasetConfigs"."order" AS "ChartDatasetConfigs.order", "ChartDatasetConfigs"."maxRecords" AS "ChartDatasetConfigs.maxRecords", "ChartDatasetConfigs"."goal" AS "ChartDatasetConfigs.goal", "ChartDatasetConfigs"."createdAt" AS "ChartDatasetConfigs.createdAt", "ChartDatasetConfigs"."updatedAt" AS "ChartDatasetConfigs.updatedAt" FROM "Chart" AS "Chart" LEFT OUTER JOIN "ChartDatasetConfig" AS "ChartDatasetConfigs" ON "Chart"."id" = "ChartDatasetConfigs"."chart_id" WHERE "Chart"."autoUpdate" > 0;',
    parameters: undefined
  },
  original: error: relation "Chart" does not exist
      at Parser.parseErrorMessage (C:\*path*\chartbrew\server\node_modules\pg-protocol\dist\parser.js:287:98)
      at Parser.handlePacket (C:\*path*\chartbrew\server\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (C:\*path*\chartbrew\server\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (C:\*path*\chartbrew\server\node_modules\pg-protocol\dist\index.js:11:42)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 106,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '1359',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1381',
    routine: 'parserOpenTable',
    sql: 'SELECT "Chart"."id", "Chart"."project_id", "Chart"."name", "Chart"."lastAutoUpdate", "Chart"."autoUpdate", "Chart"."chartData", "ChartDatasetConfigs"."id" AS "ChartDatasetConfigs.id", "ChartDatasetConfigs"."chart_id" AS "ChartDatasetConfigs.chart_id", "ChartDatasetConfigs"."dataset_id" AS "ChartDatasetConfigs.dataset_id", "ChartDatasetConfigs"."formula" AS "ChartDatasetConfigs.formula", "ChartDatasetConfigs"."datasetColor" AS "ChartDatasetConfigs.datasetColor", "ChartDatasetConfigs"."fillColor" AS "ChartDatasetConfigs.fillColor", "ChartDatasetConfigs"."fill" AS "ChartDatasetConfigs.fill", "ChartDatasetConfigs"."multiFill" AS "ChartDatasetConfigs.multiFill", "ChartDatasetConfigs"."legend" AS "ChartDatasetConfigs.legend", "ChartDatasetConfigs"."pointRadius" AS "ChartDatasetConfigs.pointRadius", "ChartDatasetConfigs"."excludedFields" AS "ChartDatasetConfigs.excludedFields", "ChartDatasetConfigs"."sort" AS "ChartDatasetConfigs.sort", "ChartDatasetConfigs"."columnsOrder" AS "ChartDatasetConfigs.columnsOrder", "ChartDatasetConfigs"."order" AS "ChartDatasetConfigs.order", "ChartDatasetConfigs"."maxRecords" AS "ChartDatasetConfigs.maxRecords", "ChartDatasetConfigs"."goal" AS "ChartDatasetConfigs.goal", "ChartDatasetConfigs"."createdAt" AS "ChartDatasetConfigs.createdAt", "ChartDatasetConfigs"."updatedAt" AS "ChartDatasetConfigs.updatedAt" FROM "Chart" AS "Chart" LEFT OUTER JOIN "ChartDatasetConfig" AS "ChartDatasetConfigs" ON "Chart"."id" = "ChartDatasetConfigs"."chart_id" WHERE "Chart"."autoUpdate" > 0;',
    parameters: undefined
  },
  sql: 'SELECT "Chart"."id", "Chart"."project_id", "Chart"."name", "Chart"."lastAutoUpdate", "Chart"."autoUpdate", "Chart"."chartData", "ChartDatasetConfigs"."id" AS "ChartDatasetConfigs.id", "ChartDatasetConfigs"."chart_id" AS "ChartDatasetConfigs.chart_id", "ChartDatasetConfigs"."dataset_id" AS "ChartDatasetConfigs.dataset_id", "ChartDatasetConfigs"."formula" AS "ChartDatasetConfigs.formula", "ChartDatasetConfigs"."datasetColor" AS "ChartDatasetConfigs.datasetColor", "ChartDatasetConfigs"."fillColor" AS "ChartDatasetConfigs.fillColor", "ChartDatasetConfigs"."fill" AS "ChartDatasetConfigs.fill", "ChartDatasetConfigs"."multiFill" AS "ChartDatasetConfigs.multiFill", "ChartDatasetConfigs"."legend" AS "ChartDatasetConfigs.legend", "ChartDatasetConfigs"."pointRadius" AS "ChartDatasetConfigs.pointRadius", "ChartDatasetConfigs"."excludedFields" AS "ChartDatasetConfigs.excludedFields", "ChartDatasetConfigs"."sort" AS "ChartDatasetConfigs.sort", "ChartDatasetConfigs"."columnsOrder" AS "ChartDatasetConfigs.columnsOrder", "ChartDatasetConfigs"."order" AS "ChartDatasetConfigs.order", "ChartDatasetConfigs"."maxRecords" AS "ChartDatasetConfigs.maxRecords", "ChartDatasetConfigs"."goal" AS "ChartDatasetConfigs.goal", "ChartDatasetConfigs"."createdAt" AS "ChartDatasetConfigs.createdAt", "ChartDatasetConfigs"."updatedAt" AS "ChartDatasetConfigs.updatedAt" FROM "Chart" AS "Chart" LEFT OUTER JOIN "ChartDatasetConfig" AS "ChartDatasetConfigs" ON "Chart"."id" = "ChartDatasetConfigs"."chart_id" WHERE "Chart"."autoUpdate" > 0;',
  parameters: {}
}

**Comment by rdr6000** [comment]
Ok so i solved it by running `npm run db:migrate` in server before running `npm run start-dev` for the first time. It should be added to the docs I think.

**Comment by razvanilin** [comment]
this issue should be solved in 3.4.0
