### ISSUE TITLE
error npm run setup

### ISSUE THREAD

**Issue by yusufabdulwahid** [chartbrew/chartbrew#184]
I'm using NodeJs v17.3.1 & npm v8.3.0.
got this error when running npm run setup

> chartbrew@v2.8.0 setup
> npm run prepareSettings && npm install && cd client && npm install && cd ../server/ && npm install

> chartbrew@v2.8.0 prepareSettings
> echo n | cp -vipr .env-template .env | true && cd client && echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true

cp: write error: Not supported
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated docsearch.js@2.6.3: This package has been deprecated and is no longer maintained. Please use @docsearch/js.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest

added 1318 packages, and audited 1319 packages in 15s

111 packages are looking for funding
  run `npm fund` for details

41 vulnerabilities (1 low, 14 moderate, 22 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'nanoid@4.0.2',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || >=18' },
npm WARN EBADENGINE   current: { node: 'v17.3.1', npm: '8.3.0' }
npm WARN EBADENGINE }
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated eslint-loader@4.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 2742 packages, and audited 2743 packages in 47s

221 packages are looking for funding
  run `npm fund` for details

56 vulnerabilities (1 low, 11 moderate, 35 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

added 920 packages, and audited 921 packages in 22s

79 packages are looking for funding
  run `npm fund` for details

22 vulnerabilities (9 moderate, 10 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

**Comment by razvanilin** [comment]
From the logs it seems that the `cp` command is not working as intended on your machine. Can you let me know what operating system are you using?

Also, the node version is an older minor version of 17 which is an odd version number for Node, meaning it can be unstable. I would suggest switching to an even number like 16 or 18

**Comment by yusufabdulwahid** [comment]
> From the logs it seems that the `cp` command is not working as intended on your machine. Can you let me know what operating system are you using?
> 
> Also, the node version is an older minor version of 17 which is an odd version number for Node, meaning it can be unstable. I would suggest switching to an even number like 16 or 18

it's windows 10 pro.
great solution. now the server can run after updating node js to version 18 and restart the server several times because of a database field error 
```
sqlMessage: "Unknown column 'Datasets.connection_id' in 'field list'",
```
and
```
sqlMessage: "Duplicate column name 'authentication'",
    sql: 'ALTER TABLE `Connection` ADD `authentication` TEXT;'
```
But when try to run the client, I got this error.
```
> client@v2.8.0 start
> npm run setup && cross-env REACT_APP_VERSION=$npm_package_version node scripts/start.js


> client@v2.8.0 setup
> echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true

cp: overwrite 'src/config/settings.js'? i ｢wds｣: Project is running at http://10.xxx.xxx.xx/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from D:\..\..\chartbrew\client\public
i ｢wds｣: 404s will fallback to /
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\..\..\chartbrew\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\..\..\chartbrew\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\..\..\chartbrew\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\..\..\chartbrew\client\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\..\..\chartbrew\client\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\..\..\chartbrew\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\..\..\chartbrew\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\..\..\chartbrew\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
D:\..\..\chartbrew\client\scripts\start.js:11
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\..\..\chartbrew\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\..\..\chartbrew\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\..\..\chartbrew\client\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\..\..\chartbrew\client\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\..\..\chartbrew\client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\..\..\chartbrew\client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\..\..\chartbrew\client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\..\..\chartbrew\client\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.0
```

**Comment by razvanilin** [comment]
I just did a quick test and it seems the UI fails to build on the latest Node v18. I will look into updating webpack to hopefully fix this issue. In the meantime, you can use Node V16 and it should work

**Comment by yusufabdulwahid** [comment]
OK. I hope it will be updated soon.
It's run great on Node js v16.
Thank's
