### ISSUE TITLE
command failed during npm install -g sequelize-cli pg

### ISSUE THREAD

**Issue by mlodimanahan** [chartbrew/chartbrew#187]
Just need your help, got this error everytime I execute "npm install -g sequelize-cli pg"

npm ERR! code 1
npm ERR! path C:\Users\mlodimanahan\node_modules\es5-ext
npm ERR! command failed
npm ERR! command bash -c node ./_postinstall.js

**Comment by razvanilin** [comment]
hey @mlodimanahan this seems entirely unrelated to Chartbrew

Why would you want to install those packages globally? I suggest following the documentation to set up the project
