### ISSUE TITLE
Passwords are not hashed in the database

### ISSUE THREAD

**Issue by kaechele** [chartbrew/chartbrew#188]
Passwords in the `User` table are encrypted but not hashed. This means that the cleartext password can be retrieved from the encrypted value in the database in conjunction with the `CB_SECRET` value using the simplecrypt decrypt function.

This is a significant security issue.

Passwords should be stored using an irreversible hash so that a person (such as an attacker or a snoopy instance administrator) with access to both the `CB_SECRET` and the database cannot retrieve cleartext passwords.

Given that Chartbrew allows users to register on their own, users may be tempted to reuse a password they use elsewhere and with that possibly giving the administrator of the Chartbrew instance access to this password.
This is especially critical where Chartbrew is hosted as a service (such as app.chartbrew.com).

Maybe this could be addressed together with #78?

**Comment by razvanilin** [comment]
Thanks for the reminder @kaechele 🙏
Our managed service already uses `brcypt` to hash passwords, but still didn't port the code over to this repo. Will look into it soon as I remember it was a relatively small change
