### ISSUE TITLE
Login issues, signup is working v2.10

### ISSUE THREAD

**Issue by vasconceloscezar** [chartbrew/chartbrew#189]
Recently I set it up Chartbrew in a Azure VM, and got it workign fine for a day or so. 

Today I tried to log in and got the following error on `server`: 

```
0|chartbrew-server  | TypeError: trust argument is required
0|chartbrew-server  |     at proxyaddr (/home/namastex/chartbrew/server/node_modules/proxy-addr/index.js:228:11)
0|chartbrew-server  |     at IncomingMessage.ip (/home/namastex/chartbrew/server/node_modules/express/lib/request.js:351:10)
0|chartbrew-server  |     at Object.keyGenerator (/home/namastex/chartbrew/server/node_modules/express-rate-limit/dist/index.cjs:187:20)
0|chartbrew-server  |     at /home/namastex/chartbrew/server/node_modules/express-rate-limit/dist/index.cjs:238:33
0|chartbrew-server  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|chartbrew-server  |     at async /home/namastex/chartbrew/server/node_modules/express-rate-limit/dist/index.cjs:221:5
```

I did a pull to update to the latest version and the issue persisted. Need some guidance on what can I do to solve this. 

Wierd is that the signup route is working. Just created a new account and its ok. The issue is on Login route apparently.

Not sure how would help, but here is our frontend: https://reportsgtg.playmeg.gg/

**Comment by razvanilin** [comment]
Hmm, I don't remember ever getting this error, but it might have to do with the way Chartbrew was set up to run. 
Googling that error, it seems it might come when the app runs behind a proxy and has `morgan` logger active (which Chartbrew does if in `development` mode)

Have you enabled the production mode with `NODE_ENV=production` by any chance?

**Comment by vasconceloscezar** [comment]
It should be, this is the alias i'm using to run the server: 

```bash
alias start_cb_server="cd ~/chartbrew/server && NODE_ENV=production pm2 start index.js --name 'chartbrew-server'"
```

**Comment by razvanilin** [comment]
Are you able to edit the Chartbrew code in your VM?

If yes, could you try adding the following in `server/index.js` at line 32:

```
const app = express();
app.settings = settings;

app.set("trust proxy", 1); // Add this line

```

Afterwards, restart the server app `pm2 reload chartbrew-server` and check if it works

**Comment by vasconceloscezar** [comment]
Great, it worked. 

FYI i got the following warning on login, even tho I don't think is anything to worry about atm: 

```bash
0|chartbrew-server  | (node:99797) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
0|chartbrew-server  | (Use `node --trace-deprecation ...` to show where the warning was created)
```

Want me to open a PR for this?
