### ISSUE TITLE
Query 'fails' at datasets

### ISSUE THREAD

**Issue by alb3rtod** [chartbrew/chartbrew#194]
I have migrated from version 2 to version 3.
I'm encountering a "The request failed" error when I execute a query to initiate a dataset. The status code on the right indicates a 404 error, along with a POST method. Therefore, I suspect the issue arises when Chartbrew attempts to post the query result in the UI.

{
  "statusCode": 404,
  "statusText": "Not Found",
  "message": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /project/undefined/chart/undefined/dataRequest/22/request</pre>\n</body>\n</html>\n"
}

When navigating to the 'Configure' tab, the chart does successfully load the data obtained by the 'failed' query. Upon returning to the 'Query' tab, the query result is indeed present.

![1](https://github.com/chartbrew/chartbrew/assets/103438142/6528dd42-1ca9-412d-b012-38365f3d0dce)
![2](https://github.com/chartbrew/chartbrew/assets/103438142/5f8d9552-6747-47ed-9b84-acb08abb8a31)
![3](https://github.com/chartbrew/chartbrew/assets/103438142/c2cecd2b-14d3-4d73-b596-c3f9d56e9691)

**Comment by razvanilin** [comment]
This issue was fixed in 32172c2a9ad5adffa9ddc74215ab2b9dc041d0e5 but the docker image is not yet updated. I just started a build now and should be available in next next few minutes. Feel free to reopen the issue if you're still seeing the problem after pulling the latest changes
