### ISSUE TITLE
Container up from v3

### ISSUE THREAD

**Issue by alb3rtod** [chartbrew/chartbrew#195]
Hi Raz! 

I want to know if it is currently possible to set up a Chartbrew container from the v3 image directly. Yesterday, I attempted to do so, but the UI never gave me access to start a project. Upon checking the logs of the container, it seemed to be looking for some tables in the local SQL database that were 'missing'. Unfortunately, I didn't save the logs. However, I managed to solve the issue by bringing up the container with the v2 image first, and then performing the migration to v3. Everything worked smoothly after that. So, my question is: Is it currently possible to bring up the container from scratch with the v3 image?

**Comment by razvanilin** [comment]
Hey @alb3rtod thanks for reporting this. I'll look into this today and see what's going on 👌

**Comment by razvanilin** [comment]
I tried to replicate the issue, but no luck on my end.

Have you pulled the latest image from `razvanilin/chartbrew`? Important to note that `razvanilin/chartbrew:v3` is now outdated and you should use `latest`

**Comment by alb3rtod** [comment]
Hi Raz!

I'm using MySQL, and Docker desktop in a windows host.

I have pulled the latest version, but it seems like the issue is still persisting. Please refer to the attached chartbrew container logs for more information.

[test_chartbrew_v3_latest.txt](https://github.com/chartbrew/chartbrew/files/14225500/test_chartbrew_v3_latest.txt)

BR.

**Comment by razvanilin** [comment]
Many thanks for the log! I'll look into this

**Comment by MrOffline77** [comment]
@razvanilin Same problem here with the latest image. Looks like the migrations are broken. 
I try to setup a fresh instance with a fresh mysql8. The Client is running, but the API server dies during startup with missing tables. Any suggestion for a workarround in the meantime ?

**Comment by razvanilin** [comment]
Hey @MrOffline77 is the `chartbrew.ChartDatasetConfig` table missing for you too?

**Comment by MrOffline77** [comment]
@razvanilin yes

**Comment by MrOffline77** [comment]
Would be cool if you could build new container versions with your migration commits, I assume they are fixing the issue ? 
Thank you :)

**Comment by razvanilin** [comment]
Hey @MrOffline77 I tried to fix the issue during a train trip, but not sure it's the final fix. I got my hands on my laptop now for a bit and just pushed an updated image. Let me know if it fixes the issue ✌️

**Comment by alb3rtod** [comment]
Hi Raz,

It seems like it's working now! I was able to bring up the container with the latest image from scratch. Great work on the project! Thank you!

**Comment by MrOffline77** [comment]
Works for me too. Thanks for the great work !

**Comment by razvanilin** [comment]
Great to hear! Thanks for testing it out ✌️
