### ISSUE TITLE
Run mongodb query return a 404

### ISSUE THREAD

**Issue by Tkd-Alex** [chartbrew/chartbrew#196]
Hello, amazing project :)

Every query mongodb i test on chartbrew It's return a 404 Not found, probably because It's trying to execute a query on a project called undefined that obviously doesn't exist on database. If I'm going to "Configure dataset", the data show up, so It's not a issue related to database connection.

![2024-02-12_15-12](https://github.com/chartbrew/chartbrew/assets/14061593/4c1ee652-9e66-45df-9b76-6427af8a258e)

**Comment by razvanilin** [comment]
Hey @Tkd-Alex 👋 are you using the latest version? (v3.01) There was a fix for this recently

**Comment by Tkd-Alex** [comment]
I'm under docker, the image was pulled 12 days ago, did you know how I can update the container?

**Comment by Tkd-Alex** [comment]
Awesome! 
I was able to update the container without any data loss and now it's working 😎

Great work!
