### ISSUE TITLE
Can't save queries

### ISSUE THREAD

**Issue by alb3rtod** [chartbrew/chartbrew#197]
Hi Raz,

I'm encountering an issue when attempting to save the query for the datasets. I enter the name, but when I click "Save," an error pop-up appears stating, "We couldn't save the query." (see image). It's worth noting that the query was successful.

![Screenshot 02-13-2024 09 03 44](https://github.com/chartbrew/chartbrew/assets/103438142/60c78cac-dd02-4062-b73f-70574454daaf)

**Comment by alb3rtod** [comment]
For the record, I pulled the latest image.

**Comment by razvanilin** [comment]
Thanks for the report! I will try and update the docker image later today. Bad internet atm

**Comment by razvanilin** [comment]
The new image is now live ✌️
