### ISSUE TITLE
Export chart in PDF format

### ISSUE THREAD

**Issue by razvanilin** [chartbrew/chartbrew#20]
Chart.js is drawn on an HTML `<canvas />` that should be straightforward to export to a PDF or any other image format.

The option to export to PDF should be included in the contextual menu of every chart (screenshot below). This shouldn't require any back-end work.

![image](https://user-images.githubusercontent.com/5342321/70851727-281c6300-1e99-11ea-86c1-f915f9cf1e80.png)

**Comment by testerslol123** [comment]
Hi sir, I would like to take this challenge.
Can you assign me for this?

**Comment by razvanilin** [comment]
> Hi sir, I would like to take this challenge hacktoberfest.
> Can you assign me for this?

Sure thing, just updated

**Comment by testerslol123** [comment]
Seems I was busy doing other project also. So I would like to give my pull request to other contributor here.
Thank you

**Comment by warisanwar** [comment]
Hey Raz!
Can I be assigned this feature?

**Comment by razvanilin** [comment]
Closed this since adding the dashboard PDF printing feature seems to work for individual charts as well.
