### ISSUE TITLE
Migrations don't support existing data

### ISSUE THREAD

**Issue by codingmatty** [chartbrew/chartbrew#200]
The migrations fail for existing databases because the `team_id` is added to `Connection` and `Dataset` tables as non-nullable before trying to backfill the data in subsequent lines.

https://github.com/chartbrew/chartbrew/blob/master/server/models/migrations/20231006073638-change-team-level-connection.js#L8
https://github.com/chartbrew/chartbrew/blob/master/server/models/migrations/20231006124553-change-team-level-dataset.js#L8

**Comment by razvanilin** [comment]
Good spot! I have no idea how this worked in my tests. Maybe some different database config

The migrations should work with the latest changes now. I also pushed an update on docker hub in case you're using that. Let me know if you still see the issue ✌️
