### ISSUE TITLE
Publish directory build does not exist! when deploying frontend to render

### ISSUE THREAD

**Issue by eurosoll** [chartbrew/chartbrew#202]
Hi

I have been been following the guide to deploying on Render and am coming up with an issue. 

I have been able to create the database and backend, but the frontend is failing every time I try to deploy.

Any help would be appreciated. Thanks

The logs are:

==> Cloning from https://github.com/xxxxxxx/chartbrew
==> Checking out commit fd8ecd64ed9a7ac3bd1570f1f7c021a7ca8bd17c in branch master
==> Using Node version 20.10.0 (default)
==> Docs on specifying a Node version: https://render.com/docs/node-version
==> Using Ruby version 3.2.2 (default)
==> Docs on specifying a Ruby version: https://render.com/docs/ruby-version
==> Installing dependencies with npm...
added 742 packages, and audited 743 packages in 24s
164 packages are looking for funding
  run `npm fund` for details
4 vulnerabilities (3 high, 1 critical)
To address issues that do not require attention, run:
  npm audit fix
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
up to date, audited 743 packages in 2s
164 packages are looking for funding
  run `npm fund` for details
4 vulnerabilities (3 high, 1 critical)
To address issues that do not require attention, run:
  npm audit fix
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
==> Using Python version 3.11.7 (default)
==> Docs on specifying a Python version: https://render.com/docs/python-version
==> Using Poetry version 1.7.1 (default)
==> Docs on specifying a Poetry version: https://render.com/docs/poetry-version
==> Installing Poetry version 1.7.1
Retrieving Poetry metadata
# Welcome to Poetry!
This will download and install the latest version of Poetry,
a dependency and package manager for Python.
It will add the `poetry` command to Poetry's bin directory, located at:
/opt/render/project/poetry/bin
You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.
Installing Poetry (1.7.1)
Installing Poetry (1.7.1): Creating environment
Installing Poetry (1.7.1): Installing Poetry
Installing Poetry (1.7.1): Creating script
Installing Poetry (1.7.1): Done
Poetry (1.7.1) is installed now. Great!
To get started you need Poetry's bin directory (/opt/render/project/poetry/bin) in your `PATH`
environment variable.
Add `export PATH="/opt/render/project/poetry/bin:$PATH"` to your shell configuration file.
Alternatively, you can call Poetry explicitly with `/opt/render/project/poetry/bin/poetry`.
You can test that everything is set up by executing:
`poetry --version`
==> Running build command 'npm install; npm run build'...
up to date, audited 743 packages in 2s
164 packages are looking for funding
  run `npm fund` for details
4 vulnerabilities (3 high, 1 critical)
To address issues that do not require attention, run:
  npm audit fix
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
> client-new@v3.1.0 build
> npm run prepareSettings && vite build
> client-new@v3.1.0 prepareSettings
> echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true
vite v5.0.10 building for production...
transforming...
✓ 3188 modules transformed.
rendering chunks...
[plugin:vite:reporter] 
(!) /opt/render/project/src/client/src/components/FeedbackForm.jsx is dynamically imported by /opt/render/project/src/client/src/containers/Main.jsx but also statically imported by /opt/render/project/src/client/src/components/Navbar.jsx, dynamic import will not move module into another chunk.
computing gzip size...
dist/index.html                                            2.40 kB │ gzip:   0.93 kB
dist/assets/stripe-connection-Mlyc4ibD.webp                4.18 kB
dist/assets/simpleAnalytics-dark-QiCa0yaA.png              4.26 kB
dist/assets/Strapi-dark-85KfiIg7.png                       4.53 kB
dist/assets/ChartMogul-dark-xN_t5yDj.png                   4.59 kB
dist/assets/mongodb-dark-9G0hIr_5.png                      5.72 kB
dist/assets/mongodb-logo-60GIcCcL.png                      6.04 kB
dist/assets/Stripe-dark-QiirBsCg.png                       7.32 kB
dist/assets/api-dark-8gL5NuQj.png                          7.49 kB
dist/assets/api-i5JsBiyy.png                               7.62 kB
dist/assets/mysql-dark-OLk-zNCD.png                        9.26 kB
dist/assets/logo_blue-891UyiPS.png                        10.65 kB
dist/assets/realtime-db-url-rvp2_b-S.webp                 10.81 kB
dist/assets/mysql-yA-h0RVO.png                            10.84 kB
dist/assets/customerio-d9GdvRQ1.png                       11.66 kB
dist/assets/customerio-dark-nhelsqSp.png                  12.34 kB
dist/assets/GoogleAnalytics-Ds26Bh7I.webp                 13.72 kB
dist/assets/googleanalytics-dark-uMrLG0sI.png             13.74 kB
dist/assets/ChartMogul-S9t9XY1_.webp                      13.94 kB
dist/assets/postgres-dark-5hzok4P2.png                    14.16 kB
dist/assets/firebase-real-time-database-JE73brAe.png      15.28 kB
dist/assets/postgres-rSivrLqB.png                         16.54 kB
dist/assets/Supabase-dark-xkPjDgxu.png                    17.37 kB
dist/assets/plausible-logo-o_4w23lp.png                   18.51 kB
dist/assets/firebase-firestore-xEgCo-ot.png               18.79 kB
dist/assets/mailgun-dark-t1cgerjO.png                     21.38 kB
dist/assets/firebase-dark-IqktMyNg.png                    23.13 kB
dist/assets/mailgun_logo-M2t3skJm.webp                    24.82 kB
dist/assets/firestore-dark-oDrCRZR_.png                   26.70 kB
dist/assets/plausible-dark-2hD7Olq5.png                   28.69 kB
dist/assets/logo_full_dark-SHvz0knG.png                   36.12 kB
dist/assets/logo_full_light-OdnqUld-.png                  40.39 kB
dist/assets/timescaledb-3GEEcsS8.jpg                     117.73 kB
dist/assets/chartbrew-auto-update-kVP02kCp.jpg           121.52 kB
dist/assets/timescaledb-dark-nismRqjc.jpeg               125.07 kB
dist/assets/dashboards_background--t47EXWH.webp          139.67 kB
dist/assets/chartmogul-template-H-SDD4GL.jpeg            238.74 kB
dist/assets/plausible-template-ZQrl0Eo6.jpeg             239.51 kB
dist/assets/mailgun-template-7iqd4uNV.jpeg               275.44 kB
dist/assets/simpleanalytics-template-FJigFIOX.jpeg       294.50 kB
dist/assets/ga-template-w0l7VPBM.jpeg                    316.95 kB
dist/assets/quick-start-video-jnU6AKwJ.jpg               353.79 kB
dist/assets/instruction-dashboard-report-sxwzQEEb.png  1,332.42 kB
dist/assets/ProjectBoard-GFniA02B.css                      5.39 kB │ gzip:   1.00 kB
dist/assets/index-JwHSlfdh.css                           211.56 kB │ gzip:  26.94 kB
dist/assets/validations-H-C24gFd.js                        0.30 kB │ gzip:   0.25 kB
dist/assets/ProjectRedirect-l-A7lbbI.js                    0.60 kB │ gzip:   0.37 kB
dist/assets/UserInvite-kgBeXzAy.js                         1.28 kB │ gzip:   0.70 kB
dist/assets/GoogleAuth-1DTvwDoB.js                         1.77 kB │ gzip:   0.91 kB
dist/assets/PasswordReset-eYck8-IU.js                      2.31 kB │ gzip:   1.12 kB
dist/assets/ManageTeam-l7m0Lcxy.js                         2.43 kB │ gzip:   1.06 kB
dist/assets/Login-Z7tJaZG8.js                              4.66 kB │ gzip:   1.78 kB
dist/assets/EmbeddedChart-ZmQ_cM3U.js                      4.98 kB │ gzip:   1.97 kB
dist/assets/ManageUser-tTMRWn2C.js                         5.06 kB │ gzip:   1.98 kB
dist/assets/Signup-wptOFkT3.js                             6.70 kB │ gzip:   2.33 kB
dist/assets/PublicDashboard-RAweY51w.js                   40.20 kB │ gzip:  13.16 kB
dist/assets/ProjectBoard-LIJtMXt6.js                     168.12 kB │ gzip:  52.48 kB
dist/assets/index-OIur3FMK.js                          2,955.81 kB │ gzip: 844.47 kB
(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 35.79s
==> Publish directory build does not exist!
==> Build failed 😞
==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys

<img width="577" alt="image" src="https://github.com/chartbrew/chartbrew/assets/28790477/3459bcd3-a4b9-4652-bc81-e26d552df14d">

<img width="749" alt="image" src="https://github.com/chartbrew/chartbrew/assets/28790477/8058e5d1-5094-453f-923c-adc3799fabe2">

**Comment by razvanilin** [comment]
Hey @eurosoll I still haven't updated the blog post to the v3 instructions, but the only changes you will have to make are: 
* replace the `client/build` directory to `client/dist`
* The `REACT_APP_` variables should be changed to `VITE_APP_` instead: https://chartbrew.com/blog/how-to-deploy-chartbrew-on-render/#:~:text=Chartbrew%20signup%20page-,Final%20touches,-The%20application%27s%20main

`REACT_APP_CLIENT_HOST ` -> `VITE_APP_CLIENT_HOST`
`REACT_APP_API_HOST` -> `VITE_APP_API_HOST`

Let me know if that works for you ✌️

**Comment by eurosoll** [comment]
Hi. Appreciate the quick help.

Yes that all worked perfectly.

Could I ask where do we put the email vars?

**Comment by razvanilin** [comment]
Hey @eurosoll, you can put the email vars in the same place where you put the DB connections vars: https://chartbrew.com/blog/how-to-deploy-chartbrew-on-render/#:~:text=CB_API_HOST%20%2D%20set%20this%20to%200.0.0.0%20like%20in%20the%20example

**Comment by razvanilin** [comment]
Closing this, but will track #207 to fix the tutorial based on the new v3 updates
