### ISSUE TITLE
Unable to Authenticate with Chartbrew Deployed on Render

### ISSUE THREAD

**Issue by AndryHTC** [chartbrew/chartbrew#211]
I am experiencing an issue with authenticating in my Chartbrew instance deployed on Render. I have followed the deployment guide provided by Chartbrew and made the necessary changes to the environment variables as described in this GitHub issue: [#207](https://github.com/chartbrew/chartbrew/issues/207)

The problem is that although the signup process seems to work correctly (I can see my user being created in the "user" table of the PostgreSQL database), I am unable to log in. When I attempt to log in, I receive an error message saying "Wrong email or password". Additionally, every front-end call results in a 401 (Unauthorized) error.

I have also tried using the `3.2.0` tag instead of the `master` branch, but the issue persists.

There are no particular error logs in the back-end (maybe some during the migrations here and there, the DB is new and clean):
```
Updated database schema to the latest version!
Running server on port 10000
==> Your service is live 🎉
Running server on port 10000
==> Deploying...
==> Using Node version 20.11.1 (default)
==> Docs on specifying a Node version: https://render.com/docs/node-version
==> Running 'NODE_ENV=production node index.js'
Running server on port 10000
==> Your service is live 🎉
==> Detected service running on port 10000
==> Docs on specifying a port: https://render.com/docs/web-services#port-detection

```
I would appreciate any assistance or guidance on resolving this authentication issue. Please let me know if you need any further information or if there are any specific steps I should take to investigate and resolve the problem.

Thank you in advance for your help!

**Comment by razvanilin** [comment]
Hey @AndryHTC I just gave it a test now and I can replicate the same issue. I can see all migrations completed correctly, so it must be something else. I'll have a look in the morning and will update with a solution

**Comment by razvanilin** [comment]
Just looked more into this and it seems the error is caused by the email encryption module. For some reason the encrypted values are not consistent and this is something that I've only seen on Render. It was on my todo list to replace that encryption module anyway, so I think I'll have to take the plunge and do it sooner now 😅

**Comment by AndryHTC** [comment]
@razvanilin can I use an older version for this? I really need it working by the end of the week

**Comment by razvanilin** [comment]
All versions use this encryption module, so unfortunately I don't think you can get it to work with any version.

I started working on a new encryption module already, but it takes a bit longer because I need be careful with writing the migrations from the old encryption module to the new one without breaking anyone's instance. Might be able to finish today-tomorrow  🤞

**Comment by AndryHTC** [comment]
@razvanilin wow. Literally a speedrun :)

**Comment by AmoonPod** [comment]
@razvanilin, same issue here. Can’t wait to see it solved. 🙏

**Comment by razvanilin** [comment]
I updated the blog post now with the latest updates and the `master` branch has the latest changes: https://chartbrew.com/blog/how-to-deploy-chartbrew-on-render/

The only change to a new deployment is to add the `CB_ENCRYPTION_KEY` to the Node web service and can safely remove the `CB_SECRET` variable.

I ran a few tests and it seems to be working fine for me when I deploy on render, but feel free to reach out if you encounter any issues ✌️

**Comment by AndryHTC** [comment]
@razvanilin Unfortunately I had to switch to Metabase because of the strict timing. I hope to get back to it in the future
