### ISSUE TITLE
MongoDB connection broken after upgrade to v3.3.0

### ISSUE THREAD

**Issue by Tkd-Alex** [chartbrew/chartbrew#217]
Hello, I'll post here a series of screenshots.
The connection via mongodb for me is completly broken. 
All the connection params saved on chartbrew was replace to a hash

![tg_image_2772999394](https://github.com/chartbrew/chartbrew/assets/14061593/760d053f-3da5-4c95-9c93-0a5c144431af)
![tg_image_2658164819](https://github.com/chartbrew/chartbrew/assets/14061593/98b73654-dedf-4210-98b6-0947278996f6)

Also I'm not able to create new connection becase I get a "success popup" but the api return a error.
![tg_image_845491876](https://github.com/chartbrew/chartbrew/assets/14061593/5dcde404-6fd5-4c31-80f9-c0fe79bc02e6)

**Comment by Tkd-Alex** [comment]
Here was my fault, the encryption key used must be an hex.

https://github.com/chartbrew/chartbrew/blob/04b923c305484ce91b179418266dd9bffe51dd61/server/modules/setUpEncryptionKeys.js#L8-L10

I've used the one highlighted

![image](https://github.com/chartbrew/chartbrew/assets/14061593/88276461-4815-408e-8dd1-c5ca563360d7)

**Comment by razvanilin** [comment]
have you added the new key in the `CB_ENCRYPTION_KEY_DEV` by any chance?

**Comment by Tkd-Alex** [comment]
Yes, I had to create a new key `crypto.randomBytes(32).toString("hex")` instead of used the one create from the website
