### ISSUE TITLE
ERR_CRYPTO_INVALID_KEYLEN

### ISSUE THREAD

**Issue by hoang3402** [chartbrew/chartbrew#219]
![image](https://github.com/chartbrew/chartbrew/assets/54090585/d7dd8046-a002-4bd1-b1c5-39beb134941d)

An error occurs when adding a new connection; it indicates success but does not function, and the option "Select a connection" cannot be selected.

(api)/team/1/connections - 400 Bad Request
```json
{
    "type": "api",
    "subType": "strapi",
    "optionsArray": [],
    "name": "Strapi",
    "authentication": {
        "type": "bearer_token",
        "token": ""
    },
    "host": "api",
    "options": [],
    "team_id": "1"
}
```

**Comment by razvanilin** [comment]
Hey @hoang3402 it looks like the `CB_ENCRYPTION_KEY` value is not the right format. You can generate a key from here: https://generate-random.org/encryption-key-generator?count=1&bytes=32&cipher=aes-256-cbc&string=&password= 

If you run this in development, the key needs to be placed in `CB_ENCRYPTION_KEY_DEV`

**Comment by razvanilin** [comment]
It looks like from #218 that the website I quoted does not generate valid keys all the time.

You can generate valid keys using the following command:

```
openssl rand -hex 32
```

Also, if you're not using 3.4.0 yet, I recommend upgrading because it has some important fixes to the encryption

**Comment by hoang3402** [comment]
I am using version 3.4.0 and I have set the CB_ENCRYPTION_KEY=JDw79w2olomOXKCgtaGpcSfQBGtjXWzhycfdk1bcCwn+y6uAI4ggKHhNJqDWSZML

**Comment by yevhenskakun** [comment]
> I am using version 3.4.0 and I have set the CB_ENCRYPTION_KEY=JDw79w2olomOXKCgtaGpcSfQBGtjXWzhycfdk1bcCwn+y6uAI4ggKHhNJqDWSZML

it should be like this:
```
CB_ENCRYPTION_KEY=7760818611ab0e6aecd0600a932e8507b4870e655c495ba119293ddee788dda7
CB_ENCRYPTION_KEY_DEV=745e62829584e037b7da09ed70f95c5c14feb8afdfe45bb29196f484c53b464a
```

**Comment by hoang3402** [comment]
okey it work
