### ISSUE TITLE
Postgresql connection string

### ISSUE THREAD

**Issue by yevhenskakun** [chartbrew/chartbrew#220]
Because the system modifies the Connection string in some way, it is impossible to execute a database query

![image](https://github.com/chartbrew/chartbrew/assets/121243396/13891a17-add8-420f-a562-34c89a06e567)

![image](https://github.com/chartbrew/chartbrew/assets/121243396/191bba3f-19eb-40d5-ba91-0153fa32ebb1)

**Comment by yevhenskakun** [comment]
If i use Connection form it works fine.

**Comment by razvanilin** [comment]
Have you created the connection using a different encryption key by any chance? If that's the case you will have to re-create the connection for it to work because the connection string cannot be decrypted

**Comment by yevhenskakun** [comment]
yup, it was the case
