### ISSUE TITLE
MongoDB `Server selection timed out after 30000 ms`

### ISSUE THREAD

**Issue by RappyTV** [chartbrew/chartbrew#224]
hey, I tried adding my MongoDB to my chartbrew instance. The problem I'm encountering is this error:
`Server selection timed out after 30000 ms`.
The exact same connection string works everywhere else (in my code, MongoDB compass etc) but is not recognized in Chartbrew. The string looks like this: `mongodb+srv://<name>:<password>@db.rappytv.com/boosts`. I also tried using the connection form but this didn't help either. Also the db allows every ip so that's not the problem. I just don't know how I'm supposed to get it running, please help :)

**Comment by razvanilin** [comment]
Hey, sorry for the delay with this one! Do you remember if there was any other error log on the server or just the `Server selection timed out...`?

Also, can you let me know what version of MongoDB are you running? I could not replicate the issue with my connections, so maybe there is something else I'm missing

**Comment by RappyTV** [comment]
Nope, there is no error log. Just the Server selection error on the app. I'm using mongo db v7.0.5

**Comment by RappyTV** [comment]
bump

**Comment by RappyTV** [comment]
nice 👍
