### ISSUE TITLE
New Dataset Name Not Appearing Immediately in Chart Edition

### ISSUE THREAD

**Issue by alb3rtod** [chartbrew/chartbrew#239]
I'm experiencing an issue where, when you create a new dataset from an existing chart that already has its own dataset, must of the time the name of the new dataset doesn't appear immediately.

![image](https://github.com/user-attachments/assets/c3e11f9a-4c6e-4c0a-83c0-7db8928bb70f)

**Comment by razvanilin** [comment]
Hey @alb3rtod I'm having a hard time understanding the issue here. Can you post a quick video or multiple screenshots showing the issue?

**Comment by alb3rtod** [comment]
Yes, sure. First, I create a dataset, save it, and then open it in a dashboard:

![image](https://github.com/user-attachments/assets/0ff7d27a-6abf-4631-b455-e64eb2a75d53)

Then, I create a new dataset directly from this chart:

![image](https://github.com/user-attachments/assets/37ef89ff-e6d2-4735-9f32-24ff6767238b)

![image](https://github.com/user-attachments/assets/da6ac97f-f408-4754-ad62-0663e649d3b9)

I save the new dataset and return to the same chart:

![image](https://github.com/user-attachments/assets/a1a6ab07-2d30-4873-82e5-010f6539d00f)

But the new dataset name is not shown in the chart view, even after a Refresh Chart action:

![image](https://github.com/user-attachments/assets/51cae757-09d1-46dd-93ab-767565cb2949)

![image](https://github.com/user-attachments/assets/5c2798c0-34fe-4857-bef2-d0ef9a628997)

Does that explain it better? Hehe, BR.

**Comment by razvanilin** [comment]
Thanks for the detailed explanation! I will look into this and try to replicate 👌
