### ISSUE TITLE
widget.js:1 [Headway Error] Element provided by selector does not exist.

### ISSUE THREAD

**Issue by 95-M** [chartbrew/chartbrew#246]

**Comment by razvanilin** [comment]
Hi there, can you please provide more background into this issue? Screenshots, behaviours, when it happens...anything can help

**Comment by razvanilin** [comment]
this is a warning from a 3rd party widget we use for the changelog and it's not interfering with the correct functioning of the site. I'll close this as it's not something worth focusing on
