### ISSUE TITLE
Add option to select a global time on a dashboard an inject the value in all the charts

### ISSUE THREAD

**Issue by razvanilin** [chartbrew/chartbrew#37]
There could be an option on the dashboard to select a date range and inject this value to all the charts present on the dashboard. This could be useful for monthly reports, for example.

**Comment by pgmaier** [comment]
I would like this to be added!

**Comment by razvanilin** [comment]
Hey @pgmaier this option is available in each dashboard here:

![Image](https://github.com/user-attachments/assets/3c619f89-96e0-4b4a-bf70-5f5bda07aa8c)

You can then select the `Date` type for the filter, and select the date range:

![Image](https://github.com/user-attachments/assets/1e9d4a0d-70cc-4cc8-9046-1f8303acf320)
