### ISSUE TITLE
Simplify the roles check in the backend

### ISSUE THREAD

**Issue by razvanilin** [chartbrew/chartbrew#44]
At the moment, checking the roles (if the current user can access the resource) requires a lot of repetitive code:

```
return projectController.findById(req.params.project_id)
      .then((project) => {
        return teamController.getTeamRole(project.team_id, req.user.id);
      })
      .then((teamRole) => {
        const permission = accessControl.can(teamRole.role).updateAny("chart");
        if (!permission.granted) {
          throw new Error(401);
        }
        // and only here everything is ready to continue
      })
```

This also makes the API routing a bit complicated as it's required to always include the project ID in the route.

BUT for starters, it will be good to make the check above shorter by modularising the access role check.

**Comment by hotborsh** [comment]
Could you please assign it to me?

**Comment by razvanilin** [comment]
@hotborsh I will unassign this task because of lack of activity, but if you'd like to resume, just let me know 👍
