### ISSUE TITLE
Directory code is missing

### ISSUE THREAD

**Issue by sdestivelle** [chartbrew/chartbrew#48]
Hi,

when you want to use the Dockerfile it returns that "npm ERR! enoent ENOENT: no such file or directory, open '/code/package.json'"
And there is no code directory on the GitHub repository.

Regards,

Steve

**Comment by razvanilin** [comment]
Hey @sdestivelle 👋 Thanks for reporting this. I'll have a look at this asap

**Comment by razvanilin** [comment]
I just committed (fb30db0) a fix for this on `master`. Can you pull the latest changes and let me know if it now builds for you?

**Comment by sdestivelle** [comment]
I've got his.

[root@localhost chartbrew]# docker-compose up -d
WARNING: The CB_DB_NAME_DEV variable is not set. Defaulting to a blank string.
WARNING: The CB_DB_USERNAME_DEV variable is not set. Defaulting to a blank string.
WARNING: The CB_DB_PASSWORD_DEV variable is not set. Defaulting to a blank string.
Building chartbrew
Step 1/11 : FROM node:10
 ---> 5010eb9431a5
Step 2/11 : WORKDIR /code
 ---> Using cache
 ---> 9749dcb3e112
Step 3/11 : COPY . .
 ---> Using cache
 ---> 2a587de5710f
Step 4/11 : RUN apt-get update && apt-get install -y rsync
 ---> Running in 26fd1386cb44
Err:1 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package rsync is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'rsync' has no installation candidate
ERROR: Service 'chartbrew' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y rsync' returned a non-zero code: 100

**Comment by razvanilin** [comment]
Can you try to update line 7 in `Dockerfile` with the following:

```
RUN apt-get update && apt-get upgrade -y && apt-get install -y rsync
```

Then run `docker-compose up --build`

**Comment by razvanilin** [comment]
`rsync` is not a dependency anymore and the whole Docker environment was revamped. If you still have issues, feel free to come back to this issue
