### ISSUE TITLE
Error when execute 'npm run db:migrate'

### ISSUE THREAD

**Issue by sdestivelle** [chartbrew/chartbrew#49]
Hi,

I've got this message when I try to initialise the database with the migrate command.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'db:migrate' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose run-script [ 'predb:migrate', 'db:migrate', 'postdb:migrate' ]
5 info lifecycle server@1.0.0-beta.9.3~predb:migrate: server@1.0.0-beta.9.3
6 info lifecycle server@1.0.0-beta.9.3~db:migrate: server@1.0.0-beta.9.3
7 verbose lifecycle server@1.0.0-beta.9.3~db:migrate: unsafe-perm in lifecycle true
8 verbose lifecycle server@1.0.0-beta.9.3~db:migrate: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/chartbrew/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle server@1.0.0-beta.9.3~db:migrate: CWD: /opt/chartbrew/server
10 silly lifecycle server@1.0.0-beta.9.3~db:migrate: Args: [ '-c', 'cd models && npx sequelize-cli db:migrate' ]
11 silly lifecycle server@1.0.0-beta.9.3~db:migrate: Returned: code: 1  signal: null
12 info lifecycle server@1.0.0-beta.9.3~db:migrate: Failed to exec db:migrate script
13 verbose stack Error: server@1.0.0-beta.9.3 db:migrate: `cd models && npx sequelize-cli db:migrate`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid server@1.0.0-beta.9.3
15 verbose cwd /opt/chartbrew/server
16 verbose Linux 3.10.0-1062.4.3.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "db:migrate"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error server@1.0.0-beta.9.3 db:migrate: `cd models && npx sequelize-cli db:migrate`
22 error Exit status 1
23 error Failed at the server@1.0.0-beta.9.3 db:migrate script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Regards,

Steve

**Comment by razvanilin** [comment]
Could you try the following:

```
cd server/models
npx sequelize-cli db:migrate
```
If it fails, the stack trace should be clearer about what's the problem

**Comment by sdestivelle** [comment]
I've got another error.

npx : 80 installé(s) en 2.044s

Sequelize CLI [Node: 10.22.0, CLI: 6.2.0, ORM: 5.22.3]

Loaded configuration file "config/config.js".
Using environment "development".
== 20191214175953-create-user: migrating =======

ERROR: Invalid default value for 'createdAt'

**Comment by razvanilin** [comment]
Did you run `npm run setup` in the project's root folder?

**Comment by razvanilin** [comment]
I'm closing this as I couldn't replicate the issue or heard from someone else about it. If you're still having problems after following the setup instructions, I can open the issue again.

**Comment by mlodimanahan** [comment]
Hi, im having some trouble when I execute the command "npm run db:migrate" the result is npm ERR! Missing script: "db:migrate"
npm ERR!   npm run
