### ISSUE TITLE
Can't sign up as new user in synology docker

### ISSUE THREAD

**Issue by franbugallo** [chartbrew/chartbrew#80]
Hi! After some ups and downs I have been able to configure chartbrew and make it run in my synology docker. The issue that I'm facing is that when I enter the frontend and try to sign-up as new user nothing happens! I mean, I complete name, mail and password but when I press the button nothing happens...

Thanks for your help

**Comment by razvanilin** [comment]
Hey @franbugallo 👋 Can you open the dev tools in the browser and see what errors you are getting in the `Networking` tab? My guess is that the front-end cannot reach the back-end application. Try and see if you can reach the back-end application yourself like so:

![image](https://user-images.githubusercontent.com/5342321/104393211-def88000-557e-11eb-8630-7a2e815b5cc2.png)

**Comment by franbugallo** [comment]
Hi @razvanilin, thank you so much for your help!.

My back-end seems to be working...
<img width="382" alt="Captura de pantalla 2021-01-13 a las 11 47 06" src="https://user-images.githubusercontent.com/72529828/104442738-c3e53a80-5595-11eb-890f-18a7131f057d.png">

I'm getting following error, but I don't see that is related to the sign-up petition itself.

<img width="823" alt="Captura de pantalla 2021-01-13 a las 11 53 38" src="https://user-images.githubusercontent.com/72529828/104442970-158dc500-5596-11eb-972e-5ae46de72d58.png">

**Comment by razvanilin** [comment]
Is your browser not saving cookies by any chance?
Also, have you tried to log in with the details you already entered during the signup? I'm just thinking that maybe the signup process had a hiccup, but your user account is actually created.

If you can view your database, it will also be good if you can check the user table and see if there's any data there.

**Comment by franbugallo** [comment]
It is saving cookies. The database is empty.
<img width="417" alt="Captura de pantalla 2021-01-13 a las 18 51 56" src="https://user-images.githubusercontent.com/72529828/104490027-9e295700-55d0-11eb-9b70-4a3af621b726.png">

Could it be that the front-end is not able to communicate with the back-end despite being up and running? I had to do a few tweeks in the env variables so that it would work in my synology. I'm almost sure that this is something wrong with this, but I have tried several confs without success.

<img width="618" alt="Captura de pantalla 2021-01-13 a las 18 56 42" src="https://user-images.githubusercontent.com/72529828/104490679-6f5fb080-55d1-11eb-93be-012812b78e41.png">

**Comment by razvanilin** [comment]
Have you set the `REACT_APP_API_HOST`? That's the one that needs to be set for the client app to find the server

`REACT_APP_API_HOST=http://your-address:3210`

I think it might be a bit confusing that there's already the `CB_API_HOST` variable, but this is used by the server and everything with `REACT_` is used by the front-end app.

**Comment by franbugallo** [comment]
I feel so dumb! That was the issue. It is working now. I promise I read the docs a thousand times but I don't know why I didn't realize about this mistake. I changed several configs but I never thought that I was missing a parameter.

Thank you so much for your assistance!

**Comment by razvanilin** [comment]
haha don't worry about it. The docs could definitely be improved though. Not to mention the docker ones 😅

I'll close this issue now, but feel free to let me know if there's anything else not working. You can join [the Discord server](https://discord.gg/KwGEbFk) if you wish
