### ISSUE TITLE
Get a bearer token (OAuth2)?

### ISSUE THREAD

**Issue by PierrickI3** [chartbrew/chartbrew#96]
Is it possible to get a bearer token via OAuth2? All I can see in the demo site is the ability to set the bearer token.

**Comment by razvanilin** [comment]
Hey @PierrickI3 , oauth2 is not currently supported for API connections (mostly because nobody asked for it yet). I'll add this to the GH project

**Comment by PierrickI3** [comment]
Thanks! Nice job by the way
