### ISSUE TITLE
Always return a generic 200 when requesting a password reset

### ISSUE THREAD

**Issue by razvanilin** [chartbrew/chartbrew#99]
This is needed to avoid situations where others can guess emails already registered in the system.

**Comment by gkydev** [comment]
Can you assign this to me please ?

**Comment by razvanilin** [comment]
@gkydev Done

**Comment by razvanilin** [comment]
@gkydev The description is a bit lacking, but basically, this request should return a 200 right away, but still start processing the password reset in the background, async. Here's the devil:  https://github.com/chartbrew/chartbrew/blob/master/server/api/UserRoute.js#L314
